# Generated by Django 5.2.6 on 2025-09-27 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rr_app', '0002_pendinguser_user_is_verified_user_verification_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_token',
        ),
    ]
