# Generated by Django 5.2.6 on 2025-09-29 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rr_app', '0005_usersession_delete_pendinguser_alter_user_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
