# Generated by Django 5.2.6 on 2025-09-28 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rr_app', '0005_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
